[package]
name = "regenerator"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
itertools.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tonic-prost-build.workspace = true
