type: Added
title: Add `Context::require_config_secret_deserialize` in Rust native API
description: |
  Adds `require_config_secret_deserialize<T>` - it's `require_config_secret` that deserializes value to `T`.
