[package]
name = "pulumi_gestalt_core_grpc"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
prost.workspace = true
tonic = { workspace = true, default-features = true }
pulumi_gestalt_core_proto = { workspace = true, features = ["connectivity"] }
tokio.workspace = true
futures.workspace = true
anyhow.workspace = true
tokio-stream.workspace = true
