site_name: Pulumi Gestalt
repo_url: https://github.com/andrzejressel/pulumi-gestalt
edit_uri: edit/main/docs/
theme:
  palette:
    scheme: slate
  name: material
  search: true
  features:
    - navigation.sections
    - navigation.indexes
    - content.tabs.link
    - content.action.edit
    - content.action.view
  custom_dir: !ENV [MKDOCS_OVERRIDE, "docs_additions/overrides/dev"]

nav:
  - index.md
#  - crates.md
  - DevBlog: https://dev.to/andrzejressel/series/30425
  - Changelog: CHANGELOG.md
  - Languages:
      - Rust:
          - languages/rust/index.md
          - rustdoc (Native): rust-docs/native/pulumi_gestalt_rust/index.html
          - rustdoc (Wasm): rust-docs/wasm/pulumi_gestalt_rust/index.html
  - Integrations:
      - Overview: integrations/overview.md
      - C FFI: integrations/c-ffi.md
      - Rust: integrations/rust.md
      - Wasm: integrations/wasm.md
#  - Internal:
#      - Internal/Output.md
#      - Internal/Serialization formats.md
#      - Internal/WIT.md
#      - Internal/Supporting new language.md

copyright: >
  Copyright &copy; 2024 - 2025 Pulumi Gestalt project

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
