site_name: Pulumi Wasm
repo_url: https://github.com/andrzejressel/pulumi-wasm
theme:
  palette:
    scheme: slate
  name: material
  search: true
  features:
    - navigation.sections
  custom_dir: !ENV [MKDOCS_OVERRIDE, "docs_additions/overrides/dev"]

nav:
  - index.md
  - crates.md
  - rustdoc: "/pulumi-wasm/rust-docs/pulumi_wasm_rust/index.html"
  - Internal:
      - Internal/Output.md
      - Internal/Serialization formats.md
      - Internal/WIT.md
      - Internal/Supporting new language.md

copyright: >
  Copyright &copy; 2024 - 2025 Pulumi Wasm project

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
