site_name: Pulumi WASM
theme:
  palette:
    scheme: slate
  name: material
  search: true

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_TOKEN
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
