[package]
name = "pulumi_wasm_cloudflare"
version = "5.43.1-0.0.0-DEV"
edition = "2021"

[dependencies]
wit-bindgen.workspace = true
pulumi_wasm_rust.workspace = true
serde.workspace = true
pulumi_wasm_wit = { workspace = true, features = ["client"] }
bon.workspace = true
pulumi_wasm_provider_common.workspace = true
