[package]
name = "pulumi_gestalt_pulumi_constant_string"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
description = "Const string values with Pulumi conversions"

[dependencies]
pulumi_gestalt_model.workspace = true
rootcause.workspace = true

[dev-dependencies]
serde_json.workspace = true
futures.workspace = true
