test_name := "raw_rust"

set windows-shell := ["pwsh.exe", "-c"]

run:
    ../../target/debug/pulumi_gestalt_example_{{test_name}}

[windows]
local-test $RUST_BACKTRACE="full":
    #!pwsh
    Set-StrictMode -Version Latest
    $ErrorActionPreference = "Stop"
    $PSNativeCommandUseErrorActionPreference = $true

    cargo build -p pulumi_gestalt_example_{{test_name}}
    $env:PULUMI_CONFIG_PASSPHRASE=" "
    pulumi destroy -y
    pulumi up -y