[package]
name = "pulumi_native_c"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
pulumi_wasm_core.workspace = true
serde_json = "1.0.137"

[build-dependencies]
cbindgen.workspace = true