[package]
name = "pulumi_gestalt_examples_common"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
assert_cmd.workspace = true
serde_json.workspace = true
anyhow.workspace = true
