[package]
name = "pulumi_native_c"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
libc.workspace = true
pulumi_gestalt_rust_integration.workspace = true

[build-dependencies]
cbindgen.workspace = true
