#ifndef __PULUMI_H__
#define __PULUMI_H__

/* Don't modify this file manually. It is autogenerated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct pulumi_composite_output_t pulumi_composite_output_t;

typedef struct pulumi_output_t pulumi_output_t;

typedef struct pulumi_context_t pulumi_context_t;

/**
 * String that may contain nulls and is not null-terminated.
 */
typedef struct pulumi_string_t {
  uint8_t *data;
  uintptr_t len;
} pulumi_string_t;

typedef struct pulumi_object_field_t {
  const char *name;
  const struct pulumi_output_t *value;
} pulumi_object_field_t;

typedef struct pulumi_register_resource_request_t {
  const char *type_;
  const char *name;
  const char *version;
  const struct pulumi_object_field_t *inputs;
  uintptr_t inputs_len;
} pulumi_register_resource_request_t;

typedef struct pulumi_invoke_resource_request_t {
  const char *token;
  const char *version;
  const struct pulumi_object_field_t *inputs;
  uintptr_t inputs_len;
} pulumi_invoke_resource_request_t;

/**
 * Arguments: Engine context, Function context, Serialized JSON value
 * Returned string must represent a JSON value;
 * Library will free the returned string
 */
typedef char *(*pulumi_mapping_function_t)(const void*, const void*, const char*);

typedef enum pulumi_config_value_t_Tag {
  PlainValue,
  Secret,
} pulumi_config_value_t_Tag;

typedef struct pulumi_config_value_t {
  pulumi_config_value_t_Tag tag;
  union {
    struct {
      char *plain_value;
    };
    struct {
      struct pulumi_output_t *secret;
    };
  };
} pulumi_config_value_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void pulumi_free_string(struct pulumi_string_t *value);

struct pulumi_context_t *pulumi_create_context(const void *context);

void pulumi_finish(struct pulumi_context_t *ctx);

void pulumi_destroy_context(struct pulumi_context_t *ctx);

struct pulumi_output_t *pulumi_create_output(struct pulumi_context_t *ctx,
                                             const char *value,
                                             bool secret);

struct pulumi_composite_output_t *pulumi_register_resource(struct pulumi_context_t *ctx,
                                                           const struct pulumi_register_resource_request_t *request);

struct pulumi_composite_output_t *pulumi_invoke_resource(struct pulumi_context_t *ctx,
                                                         const struct pulumi_invoke_resource_request_t *request);

struct pulumi_output_t *pulumi_output_map(struct pulumi_context_t *ctx,
                                          const struct pulumi_output_t *output,
                                          const void *function_context,
                                          pulumi_mapping_function_t function);

struct pulumi_output_t *pulumi_output_combine(const struct pulumi_output_t *output,
                                              const struct pulumi_output_t *const *outputs,
                                              uintptr_t outputs_size);

void pulumi_output_add_to_export(const struct pulumi_output_t *value, const char *name);

struct pulumi_output_t *pulumi_composite_output_get_field(struct pulumi_composite_output_t *output,
                                                          const char *field_name);

/**
 * Receives value from configuration
 * `name`: Configuration bag's logical name. If null, the default (project name) is used.
 * `key`: Config key. Cannot be null
 *
 * Returns null when the value is not found
 */
struct pulumi_config_value_t *pulumi_config_get_value(struct pulumi_context_t *ctx,
                                                      const char *name,
                                                      const char *key);

void pulumi_config_free(struct pulumi_config_value_t *value);

/**
 * Returns protobuf encoded schema for the provider.
 * Modules for provider can be found in Pulumi registry on left side with (M) icon:
 * - [AWS](https://www.pulumi.com/registry/packages/aws/)
 * - [Azure](https://www.pulumi.com/registry/packages/azure/)
 * - [GCP](https://www.pulumi.com/registry/packages/gcp/)
 *
 * Empty modules list means that no modules are used.
 * To use all modules, pass null for the modules pointer and 0 for the size.
 */
struct pulumi_string_t *pulumi_get_schema(const char *provider_name,
                                          const char *provider_version,
                                          const char *const *modules,
                                          uintptr_t modules_size);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* __PULUMI_H__ */
