[package]
name = "cargo-pulumi-gen"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true
pulumi_wasm_generator.workspace = true
anyhow.workspace = true