set windows-shell := ["pwsh.exe", "-c"]

[windows]
pulumi-test-regenerate-schema-json:
    pulumi plugin rm resource test -y
    go build
    pulumi package get-schema ./pulumi-test.exe > schema.json

[unix]
pulumi-test-regenerate-schema-json:
    pulumi plugin rm resource test -y
    go build
    pulumi package get-schema ./pulumi-test > schema.json

[windows]
pulumi-test-install:
    go build
    pulumi plugin install resource test 0.1 --file ./pulumi-test.exe

[unix]
pulumi-test-install:
    go build
    pulumi plugin install resource test 0.1 --file ./pulumi-test

fmt:
    go fmt .