[package]
name = "pulumi_gestalt_rust_adapter_native"
version.workspace = true
edition.workspace = true

[dependencies]
serde_json.workspace = true
pulumi_gestalt_rust_integration.workspace = true
pulumi_gestalt_rust_adapter.workspace = true
serde.workspace = true

[lints]
workspace = true
