[package]
name = "pulumi_gestalt_adapter_wasm_component_creator"
version.workspace = true
edition.workspace = true

[dependencies]
wac-graph.workspace = true
anyhow.workspace = true
directories.workspace = true
tokio.workspace = true
regex.workspace = true
log.workspace = true
async-trait.workspace = true
itertools.workspace = true
reqwest.workspace = true

[dev-dependencies]
wit-component = { workspace = true, features=["dummy-module"] }
wit-parser.workspace = true
