[test-groups]
generator-test = { max-threads = 4 }

[profile.default.junit]
path = "junit.xml"

[[profile.default.overrides]]
filter = 'package(pulumi_wasm_generator) and kind(test)'
test-group = 'generator-test'
