// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PclProtobufProgram {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<Node>,
    #[prost(message, repeated, tag = "2")]
    pub plugins: ::prost::alloc::vec::Vec<PluginReference>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PluginReference {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Node {
    #[prost(oneof = "node::Value", tags = "1, 2, 3, 4, 5")]
    pub value: ::core::option::Option<node::Value>,
}
/// Nested message and enum types in `Node`.
pub mod node {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(message, tag = "1")]
        Resource(super::Resource),
        #[prost(message, tag = "2")]
        LocalVariable(super::LocalVariable),
        #[prost(message, tag = "3")]
        ConfigVariable(super::ConfigVariable),
        #[prost(message, tag = "4")]
        OutputVariable(super::OutputVariable),
        #[prost(message, tag = "5")]
        PulumiBlock(super::PulumiBlock),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PulumiBlock {
    #[prost(message, optional, tag = "1")]
    pub required_version_range: ::core::option::Option<Expression>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Resource {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub logical_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub token: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub inputs: ::prost::alloc::vec::Vec<ResourceInput>,
    #[prost(message, optional, tag = "5")]
    pub options: ::core::option::Option<ResourceOptions>,
    #[prost(string, optional, tag = "6")]
    pub provider_name: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResourceInput {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<Expression>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResourceOptions {
    #[prost(message, optional, tag = "1")]
    pub depends_on: ::core::option::Option<Expression>,
    #[prost(message, optional, tag = "2")]
    pub protect: ::core::option::Option<Expression>,
    #[prost(message, optional, tag = "3")]
    pub parent: ::core::option::Option<Expression>,
    #[prost(message, optional, tag = "4")]
    pub ignore_changes: ::core::option::Option<Expression>,
    #[prost(message, optional, tag = "5")]
    pub provider: ::core::option::Option<Expression>,
    #[prost(message, optional, tag = "6")]
    pub version: ::core::option::Option<Expression>,
    #[prost(message, optional, tag = "7")]
    pub range: ::core::option::Option<Expression>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LocalVariable {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub logical_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub value: ::core::option::Option<Expression>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigVariable {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub logical_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub config_type: ::core::option::Option<ConfigType>,
    #[prost(message, optional, tag = "4")]
    pub default_value: ::core::option::Option<Expression>,
    #[prost(bool, tag = "5")]
    pub secret: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigType {
    #[prost(oneof = "config_type::Value", tags = "1, 2, 3, 4, 5, 6")]
    pub value: ::core::option::Option<config_type::Value>,
}
/// Nested message and enum types in `ConfigType`.
pub mod config_type {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(message, tag = "1")]
        StringType(super::Empty),
        #[prost(message, tag = "2")]
        NumberType(super::Empty),
        #[prost(message, tag = "3")]
        IntType(super::Empty),
        #[prost(message, tag = "4")]
        BoolType(super::Empty),
        #[prost(message, tag = "5")]
        ListType(::prost::alloc::boxed::Box<super::ConfigType>),
        #[prost(message, tag = "6")]
        MapType(::prost::alloc::boxed::Box<super::ConfigType>),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TupleExpressionType {
    #[prost(message, repeated, tag = "1")]
    pub element_types: ::prost::alloc::vec::Vec<ExpressionType>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObjectExpressionType {
    #[prost(map = "string, message", tag = "1")]
    pub properties: ::std::collections::HashMap<::prost::alloc::string::String, ExpressionType>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnionExpressionType {
    #[prost(message, repeated, tag = "1")]
    pub element_types: ::prost::alloc::vec::Vec<ExpressionType>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExpressionType {
    #[prost(
        oneof = "expression_type::Value",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12"
    )]
    pub value: ::core::option::Option<expression_type::Value>,
}
/// Nested message and enum types in `ExpressionType`.
pub mod expression_type {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(message, tag = "1")]
        StringType(super::Empty),
        #[prost(message, tag = "2")]
        NumberType(super::Empty),
        #[prost(message, tag = "3")]
        IntType(super::Empty),
        #[prost(message, tag = "4")]
        BoolType(super::Empty),
        #[prost(message, tag = "5")]
        ListType(::prost::alloc::boxed::Box<super::ExpressionType>),
        #[prost(message, tag = "6")]
        MapType(::prost::alloc::boxed::Box<super::ExpressionType>),
        #[prost(message, tag = "7")]
        OutputType(::prost::alloc::boxed::Box<super::ExpressionType>),
        #[prost(message, tag = "8")]
        TupleType(super::TupleExpressionType),
        #[prost(message, tag = "9")]
        DynamicType(super::Empty),
        #[prost(message, tag = "10")]
        ObjectType(super::ObjectExpressionType),
        #[prost(message, tag = "11")]
        NoneType(super::Empty),
        #[prost(message, tag = "12")]
        UnionType(super::UnionExpressionType),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OutputVariable {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub logical_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub value: ::core::option::Option<Expression>,
    #[prost(message, optional, tag = "4")]
    pub expression_type: ::core::option::Option<ExpressionType>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Expression {
    #[prost(message, optional, tag = "13")]
    pub r#type: ::core::option::Option<ExpressionType>,
    #[prost(
        oneof = "expression::Value",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12"
    )]
    pub value: ::core::option::Option<expression::Value>,
}
/// Nested message and enum types in `Expression`.
pub mod expression {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(message, tag = "1")]
        LiteralValueExpression(super::LiteralValueExpression),
        #[prost(message, tag = "2")]
        TemplateExpression(super::TemplateExpression),
        #[prost(message, tag = "3")]
        IndexExpression(::prost::alloc::boxed::Box<super::IndexExpression>),
        #[prost(message, tag = "4")]
        ObjectConsExpression(super::ObjectConsExpression),
        #[prost(message, tag = "5")]
        TupleConsExpression(super::TupleConsExpression),
        #[prost(message, tag = "6")]
        FunctionCallExpression(super::FunctionCallExpression),
        #[prost(message, tag = "7")]
        RelativeTraversalExpression(::prost::alloc::boxed::Box<super::RelativeTraversalExpression>),
        #[prost(message, tag = "8")]
        ScopeTraversalExpression(super::ScopeTraversalExpression),
        #[prost(message, tag = "9")]
        AnonymousFunctionExpression(::prost::alloc::boxed::Box<super::AnonymousFunctionExpression>),
        #[prost(message, tag = "10")]
        ConditionalExpression(::prost::alloc::boxed::Box<super::ConditionalExpression>),
        #[prost(message, tag = "11")]
        BinaryOpExpression(::prost::alloc::boxed::Box<super::BinaryOpExpression>),
        #[prost(message, tag = "12")]
        UnaryOpExpression(::prost::alloc::boxed::Box<super::UnaryOpExpression>),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LiteralValueExpression {
    #[prost(oneof = "literal_value_expression::Value", tags = "1, 2, 3, 4")]
    pub value: ::core::option::Option<literal_value_expression::Value>,
}
/// Nested message and enum types in `LiteralValueExpression`.
pub mod literal_value_expression {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(bool, tag = "1")]
        UnknownValue(bool),
        #[prost(string, tag = "2")]
        StringValue(::prost::alloc::string::String),
        #[prost(double, tag = "3")]
        NumberValue(f64),
        #[prost(bool, tag = "4")]
        BoolValue(bool),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TemplateExpression {
    #[prost(message, repeated, tag = "1")]
    pub parts: ::prost::alloc::vec::Vec<Expression>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IndexExpression {
    #[prost(message, optional, boxed, tag = "1")]
    pub collection: ::core::option::Option<::prost::alloc::boxed::Box<Expression>>,
    #[prost(message, optional, boxed, tag = "2")]
    pub key: ::core::option::Option<::prost::alloc::boxed::Box<Expression>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObjectConsExpression {
    #[prost(map = "string, message", tag = "1")]
    pub properties: ::std::collections::HashMap<::prost::alloc::string::String, Expression>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TupleConsExpression {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<Expression>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FunctionCallExpression {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub args: ::prost::alloc::vec::Vec<FunctionCallArgument>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FunctionCallArgument {
    #[prost(message, optional, tag = "1")]
    pub value: ::core::option::Option<Expression>,
    #[prost(message, optional, tag = "2")]
    pub r#type: ::core::option::Option<Type>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Type {
    #[prost(oneof = "r#type::Value", tags = "1, 2, 3, 4, 5, 6")]
    pub value: ::core::option::Option<r#type::Value>,
}
/// Nested message and enum types in `Type`.
pub mod r#type {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(message, tag = "1")]
        BoolType(super::Empty),
        #[prost(message, tag = "2")]
        IntType(super::Empty),
        #[prost(message, tag = "3")]
        NumberType(super::Empty),
        #[prost(message, tag = "4")]
        StringType(super::Empty),
        #[prost(message, tag = "5")]
        Composite(super::Empty),
        #[prost(message, tag = "6")]
        OutputType(::prost::alloc::boxed::Box<super::Type>),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelativeTraversalExpression {
    #[prost(message, optional, boxed, tag = "1")]
    pub source: ::core::option::Option<::prost::alloc::boxed::Box<Expression>>,
    #[prost(message, optional, tag = "2")]
    pub traversal: ::core::option::Option<Traversal>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScopeTraversalExpression {
    #[prost(string, tag = "1")]
    pub root_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub traversal: ::core::option::Option<Traversal>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnonymousFunctionExpression {
    #[prost(message, optional, boxed, tag = "1")]
    pub body: ::core::option::Option<::prost::alloc::boxed::Box<Expression>>,
    #[prost(string, repeated, tag = "2")]
    pub parameters: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConditionalExpression {
    #[prost(message, optional, boxed, tag = "1")]
    pub condition: ::core::option::Option<::prost::alloc::boxed::Box<Expression>>,
    #[prost(message, optional, boxed, tag = "2")]
    pub true_expr: ::core::option::Option<::prost::alloc::boxed::Box<Expression>>,
    #[prost(message, optional, boxed, tag = "3")]
    pub false_expr: ::core::option::Option<::prost::alloc::boxed::Box<Expression>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BinaryOpExpression {
    #[prost(enumeration = "Operation", tag = "1")]
    pub operation: i32,
    #[prost(message, optional, boxed, tag = "2")]
    pub left: ::core::option::Option<::prost::alloc::boxed::Box<Expression>>,
    #[prost(message, optional, boxed, tag = "3")]
    pub right: ::core::option::Option<::prost::alloc::boxed::Box<Expression>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnaryOpExpression {
    #[prost(enumeration = "Operation", tag = "1")]
    pub operation: i32,
    #[prost(message, optional, boxed, tag = "2")]
    pub operand: ::core::option::Option<::prost::alloc::boxed::Box<Expression>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Traversal {
    #[prost(message, repeated, tag = "1")]
    pub each: ::prost::alloc::vec::Vec<Traverser>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Traverser {
    #[prost(oneof = "traverser::Value", tags = "1, 2, 3, 4")]
    pub value: ::core::option::Option<traverser::Value>,
}
/// Nested message and enum types in `Traverser`.
pub mod traverser {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(message, tag = "1")]
        TraverseAttr(super::TraverseAttr),
        #[prost(message, tag = "2")]
        TraverseIndex(super::TraverseIndex),
        #[prost(message, tag = "3")]
        TraverseRoot(super::TraverseRoot),
        #[prost(message, tag = "4")]
        TraverseSplat(super::TraverseSplat),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TraverseAttr {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TraverseIndex {
    #[prost(oneof = "traverse_index::Value", tags = "1, 2")]
    pub value: ::core::option::Option<traverse_index::Value>,
}
/// Nested message and enum types in `TraverseIndex`.
pub mod traverse_index {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Value {
        #[prost(int64, tag = "1")]
        IntIndex(i64),
        #[prost(string, tag = "2")]
        StringIndex(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TraverseRoot {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TraverseSplat {
    #[prost(message, optional, tag = "1")]
    pub each: ::core::option::Option<Traversal>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Operation {
    Add = 0,
    Divide = 1,
    Equal = 2,
    GreaterThan = 3,
    GreaterThanOrEqual = 4,
    LessThan = 5,
    LessThanOrEqual = 6,
    LogicalAnd = 7,
    LogicalOr = 8,
    Modulo = 9,
    Multiply = 10,
    NotEqual = 11,
    Subtract = 12,
    LogicalNot = 13,
    Negate = 14,
}
impl Operation {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Add => "ADD",
            Self::Divide => "DIVIDE",
            Self::Equal => "EQUAL",
            Self::GreaterThan => "GREATER_THAN",
            Self::GreaterThanOrEqual => "GREATER_THAN_OR_EQUAL",
            Self::LessThan => "LESS_THAN",
            Self::LessThanOrEqual => "LESS_THAN_OR_EQUAL",
            Self::LogicalAnd => "LOGICAL_AND",
            Self::LogicalOr => "LOGICAL_OR",
            Self::Modulo => "MODULO",
            Self::Multiply => "MULTIPLY",
            Self::NotEqual => "NOT_EQUAL",
            Self::Subtract => "SUBTRACT",
            Self::LogicalNot => "LOGICAL_NOT",
            Self::Negate => "NEGATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ADD" => Some(Self::Add),
            "DIVIDE" => Some(Self::Divide),
            "EQUAL" => Some(Self::Equal),
            "GREATER_THAN" => Some(Self::GreaterThan),
            "GREATER_THAN_OR_EQUAL" => Some(Self::GreaterThanOrEqual),
            "LESS_THAN" => Some(Self::LessThan),
            "LESS_THAN_OR_EQUAL" => Some(Self::LessThanOrEqual),
            "LOGICAL_AND" => Some(Self::LogicalAnd),
            "LOGICAL_OR" => Some(Self::LogicalOr),
            "MODULO" => Some(Self::Modulo),
            "MULTIPLY" => Some(Self::Multiply),
            "NOT_EQUAL" => Some(Self::NotEqual),
            "SUBTRACT" => Some(Self::Subtract),
            "LOGICAL_NOT" => Some(Self::LogicalNot),
            "NEGATE" => Some(Self::Negate),
            _ => None,
        }
    }
}
