[package]
name = "pulumi_wasm"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen-rt.workspace = true
serde.workspace = true
serde_json.workspace = true
pulumi_wasm_common.workspace = true
log.workspace = true
pulumi_wasm_core.workspace = true
pulumi_wasm_proto.workspace = true
prost.workspace = true

[package.metadata.component]
package = "component:pulumi-wasm"

[package.metadata.component.target.dependencies]
"component:pulumi-wasm-external" = { path = "../wit/wit/deps/pulumi-wasm-external.wit" }

[package.metadata.component.target]
path = "../wit/wit/world.wit"
world = "pulumi-wasm"
