[package]
name = "pulumi_gestalt_adapter_c_core"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow.workspace = true
pulumi_gestalt_core_core.workspace = true
serde_json.workspace = true
pulumi_gestalt_core_grpc.workspace = true
pulumi_gestalt_core_proto.workspace = true
uuid.workspace = true
libc.workspace = true

[build-dependencies]
cbindgen.workspace = true