[package]
name = "pulumi_wasm_generator"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true
pulumi_wasm_generator_lib.workspace = true
anyhow.workspace = true
tempfile = "3.14.0"