name: Clean cache

on:
  push:
    branches:
      - clean-cache
  workflow_dispatch:

permissions:
  actions: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - run: gh cache delete --all -R $GITHUB_REPOSITORY
