name: Clean cache

on:
  schedule:
    - cron: '0 0 * * FRI'
  workflow_dispatch: { }

permissions:
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: gh cache delete --all -R $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ github.token }}
