name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
          ${{ runner.os }}-cargo-
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "25.3"
    - name: Build
      run: |
        cargo install cargo-component@0.9.0 --locked || which cargo-component
        cargo build --verbose
        cargo component build -p pulumi_wasm --verbose
        cargo component build -p pulumi_wasm_random --verbose
        cargo component build -p pulumi_rust_wasm --verbose
        cargo component build -p pulumi_wasm_main --verbose
    - name: Run tests
      run: cargo test --all --verbose
