name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: |
        cargo install cargo-component@0.7.1
        cargo build --verbose
        cargo component build -p pulumi_wasm --verbose
        cargo component build -p pulumi_wasm_random --verbose
        cargo component build -p pulumi_rust_wasm --verbose
        cargo component build -p pulumi_wasm_main --verbose
    - name: Run tests
      run: cargo test --verbose
